app:  
  imageName: lorenzodagostinorad/next-example
  imageTag: latest
  replica: 1
  service:
    internalPort: 3000
    api:
      endpoint: "service-go"
      port: 3000
  resources: {}

service:
  type: ClusterIP